### ISSUE TITLE
Entwickler möchte sich via REST Schnittstelle bewerben (1. Version für CodersBay)

### ISSUE THREAD

**Issue by ChrisKofler** [Gepardec/weckdengeparden#1]
Idee: Entwickler sollen sich via einer technischen Schnittstelle bewerben.
Warum: 
* um eine gewisse Motivation  und technische Basis-Kompetenz zu beweisen
* weil's ungewöhnlich ist (und wir auffallen wollen)

Wie
* via REST
* URL: https://weckdengepardenindir.xxxxx. cloud.itandtel.at

Service: Challenges abfragen
```
getChallenge ()
   challenge {
      id = 1;
      question = "1 Notebook und eine Maus kosten zusammen 1100 Euro. Der Notebook kostet 1000 Euro mehr als die Maus. Wieviel kostet die Maus?"
   }
```

Service: Challenge beantworten
```
answerChallenge {
   firstName; // String
   lastName; // String
   email; // String
   phone; // String, optional
   challengeId; // Int
   challengeAnswer; // String
   cv; // base64 encoded PDF, optional
   messageToGepardec; // String, optional
}

```

**Wenn die Challenge korrekt beantwortet wird** antwortet das Service mit
"Danke! Du hast den Geparden in dir erweckt und wir melden uns in den nächsten Tagen bei dir! Lg, Michael Sollberger"
... und wird an karriere@gepardec.com weitergeleitet.

**Wenn die Challenge-Frage falsch beantwortet wird** antwortet das Service mit
"Sorry, die Antwort ist falsch. Denk' nochmal in Ruhe darüber nach und versuch es noch einmal."

**Absender-Adresse**
* service@gepardec.com (weckdengepardenindir REST Service)

**Subject**
Bewerbung als Entwickler via REST Service (firstname lastname)

**Body**
firstName: <firstName>
lastName: <lastName>
email: <email>
phone: <phone>
challengeId: <challengeId>
challengeAnswer: <challengeAnswer>
messageToGepardec: <messageToGepardec>

**Attachment** (wenn vorhanden)
<cv>

**Comment by ChrisKofler** [comment]
@cchet : in der Doku sind noch nicht alle Params und es ist ein Absatz doppelt.
![image](https://user-images.githubusercontent.com/20546046/69425468-36a8ac00-0d2b-11ea-9be8-253973127fa4.png)

**Comment by cchet** [comment]
@phiwu-gpdec @ChrisKofler 

Mailing ist falsch konfiguriert. Exceptions sollten wir ebenfalls catchen und nicht 505 mit stacktrace zurückgeben.

14:58:38 ERROR [or.jb.re.re.i18n] (vert.x-eventloop-thread-1) RESTEASY002020: Unhandled asynchronous exception, sending back 500: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:25
--
  | Caused by: java.net.ConnectException: Connection refused
  | at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
  | at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
  | at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
  | at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ChrisKofler** [comment]
ja ... @phiwu-gpdec : Bitte Mailing dringend fixen!

**Comment by cchet** [comment]
@ChrisKofler 
Ist gefixed und deployed, bitte testen.

**Comment by ChrisKofler** [comment]
kleiner Encoding Bug noch: In der Antwort werden die Sonderzeichen nicht korrekt aufgelöst:

 ... uns in den **nÃ¤chsten** Tagen bei dir!  ...

Liegts an mir? Einfache Lösung wäre, den Umlaut durch "ae" zu ersetzen ...

**Comment by phiwu-gpdec** [comment]
@cchet Problem sollte behoben sein, bitte deployen.

@ChrisKofler bitte dann testen, bei mir stimmt der output jetzt.
